spring.application.name=ulti app

server.port=8888

spring.datasource.url=jdbc:postgresql://localhost:5432/ulti
spring.datasource.username=ulti
spring.datasource.password=ultipw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true

